MUTANTS = {
    0: {'label': 'original',
        'mutations': []},
    1: {'label': 'fake1',
        'mutations': [(1135, 'V')]},
    2: {'label': 'fake2',
        'mutations': [(1135, 'E')]},
    3: {'label': 'fake3',
        'mutations': [(1135, 'Q')]},
    4: {'label': 'fake4',
        'mutations': [(1135, 'R')]},
    5: {'label': 'fake5',
        'mutations': [(1135, 'A')]},
    6: {'label': 'fake6',
        'mutations': [(1135, 'M')]},
    7: {'label': 'fake7',
        'mutations': [(1135, 'T')]},
    8: {'label': 'fake8',
        'mutations': [(1135, 'W')]}
}
